Importar bibliotecas

In [1]:
import numpy as np # computação científica - utilizada nas curvas gaussinas

import matplotlib.pyplot as plt # para geração de gráficos

from sklearn.metrics import confusion_matrix, roc_curve, roc_auc_score, precision_recall_curve, auc # para a matrix de confusão

from sklearn.neural_network import MLPClassifier # é utilizada para criar e treinar diferentes modelos de RNA com diversas combinações de hiperparâmetros

import joblib
import os

Importar as variáveis usadas durante o treinamento

In [2]:
#IMPORTANDO O CÓDIGO DA FASE 2

# No momento que rodei todo o código (o da fase 2, aquele que enviei para a professora, junto com os seus resultados que foram gerados, eu MANDEI EXPORTAR LÁ NO COMEÇO AS SUAS VARIÁVEIS do conjunto de treinamento e teste)
# caminho e nome do arquivo Python que você EXPORTOU
arquivo_python = 'variaveis_mlp.py'

# Importar as variáveis do arquivo Python
variaveis_importadas = joblib.load(arquivo_python)

# Atribuir as variáveis importadas a variáveis locais
V1_norm_treino, V1_norm_teste, V2_norm_treino, V2_norm_teste, V7_norm_treino, V7_norm_teste, V8_norm_treino, V8_norm_teste, V12_norm_treino, V12_norm_teste, V14_norm_treino, V14_norm_teste, x_treino, x_teste, y_de_treino, y_de_teste = variaveis_importadas


# Importar variável (no mesmo momento citado no 2º coment. desse bloco, eu também exportei a lista para armazenar as estatísticas dos modelos treinados e a lista com os modelos treinados)
arquivo_python = 'estatisticas_modelos_e_lista_de_modelos_mlp.py'

# Importar a lista de estatísticas do arquivo Python
todos_os_modelos = joblib.load(arquivo_python)

Testar cada modelo e salvar os resultados em um arquivo de texto:

Carregar os modelos treinados

In [3]:
pasta_modelos = 'modelos'
lista_modelos = []

# Listar todos os arquivos na pasta de modelos
arquivos_modelos = os.listdir(pasta_modelos)

# Carregar cada modelo na lista
for arquivo in arquivos_modelos:
    caminho_arquivo = os.path.join(pasta_modelos, arquivo)
    modelo = joblib.load(caminho_arquivo)
    lista_modelos.append(modelo)

Calcular a média do desempenho do conjunto de redes iguais:

In [4]:
# Criar um arquivo de texto para salvar os resultados
arquivo_resultados = 'resultados_unicos_e_por_grupo.txt'

# Dicionário para armazenar os modelos agrupados por hiperparâmetros e suas respectivas acurácias
modelos_agrupados = {}

# Abrir o arquivo de texto para escrever os resultados
with open(arquivo_resultados, 'w') as file:
    # Testar cada modelo e salvar os resultados
    for i, modelo in enumerate(lista_modelos):
        y_pred = modelo.predict(x_teste)
        accuracy = np.mean(y_pred == y_de_teste) * 100
        conf_matrix = confusion_matrix(y_de_teste, y_pred)

        # Obter os hiperparâmetros do modelo atual
        hiperparametros = (modelo.hidden_layer_sizes, modelo.learning_rate_init, modelo.momentum)

        # Escrever os resultados no arquivo de texto
        file.write(f"Modelo {i+1}\n")
        file.write(f"Acurácia: {accuracy:.2f}\n")
        file.write(f"Matriz de Confusão:\n{conf_matrix}\n\n")

        # Adicionar a acurácia do modelo ao grupo correspondente no dicionário
        if hiperparametros in modelos_agrupados:
            modelos_agrupados[hiperparametros].append(accuracy)
        else:
            modelos_agrupados[hiperparametros] = [accuracy]

# Calcular a média do desempenho para cada grupo de modelos com os mesmos hiperparâmetros
with open(arquivo_resultados, 'a') as file:
    file.write("Média do desempenho para cada grupo de modelos:\n")
    for hiperparametros, acuracias in modelos_agrupados.items():
        media_desempenho_grupo = np.mean(acuracias)
        file.write(f"Hiperparâmetros: {hiperparametros}\n")
        file.write(f"Média do desempenho: {media_desempenho_grupo:.2f}\n\n")


In [5]:
# Calcular a média do desempenho (todas as redes)
acuracias = [np.mean(modelo.predict(x_teste) == y_de_teste) * 100 for modelo in lista_modelos]
media_desempenho = np.mean(acuracias)

print("Média do desempenho geral:", media_desempenho)


Média do desempenho geral: 71.27362055933486


Selecionar as 10 melhores redes com base na acurácia média:

In [6]:
# Verificar o tipo do objeto carregado
print(type(todos_os_modelos))

<class 'list'>


In [7]:
# Verificar as chaves presentes em um dos elementos da lista (assumindo que a lista não está vazia)
if todos_os_modelos:
    chaves_do_primeiro_elemento = todos_os_modelos[0].keys()
    print("Chaves presentes no primeiro elemento da lista:")
    print(chaves_do_primeiro_elemento)
else:
    print("A lista 'todos_os_modelos' está vazia.")

Chaves presentes no primeiro elemento da lista:
dict_keys(['hidden_layer_sizes', 'learning_rate_init', 'momentum', 'accuracy'])


In [8]:
# Ordenar os modelos pelas maiores acurácias primeiro.
todos_os_modelos.sort(key=lambda x: x["accuracy"], reverse=True)

# Selecionar as 10 melhores redes
melhores_10_redes = todos_os_modelos[:10]

# Imprimir as 10 melhores redes com suas acurácias
print("As 10 Melhores Redes:")
for i, modelo_info in enumerate(melhores_10_redes):
    print(f"Modelo {i+1}")
    print("Hiperparâmetros:", modelo_info["hidden_layer_sizes"], modelo_info["learning_rate_init"], modelo_info["momentum"])
    print("Acurácia:", modelo_info["accuracy"])
    print()

As 10 Melhores Redes:
Modelo 1
Hiperparâmetros: (30, 15) 0.1 0.99
Acurácia: 0.7968379446640317

Modelo 2
Hiperparâmetros: (30, 15) 0.01 0.9
Acurácia: 0.7960474308300395

Modelo 3
Hiperparâmetros: (30, 15) 0.01 0.9
Acurácia: 0.7873517786561266

Modelo 4
Hiperparâmetros: (20, 10) 0.01 0.9
Acurácia: 0.7873517786561265

Modelo 5
Hiperparâmetros: (20, 10) 0.2 0.9
Acurácia: 0.7869565217391304

Modelo 6
Hiperparâmetros: (30, 15) 0.01 0.9
Acurácia: 0.7869565217391304

Modelo 7
Hiperparâmetros: (30, 15) 0.01 0.9
Acurácia: 0.7782608695652173

Modelo 8
Hiperparâmetros: (30, 15) 0.01 0.99
Acurácia: 0.7778656126482214

Modelo 9
Hiperparâmetros: (20, 10) 0.01 0.9
Acurácia: 0.7703557312252964

Modelo 10
Hiperparâmetros: (20, 10) 0.1 0.9
Acurácia: 0.7703557312252964



Teste individual de cada uma das 10 melhores - e depois a seleção do melhor / com o melhor desempenho aqui:

In [9]:
from sklearn.metrics import confusion_matrix

# Variáveis para acompanhar o melhor modelo e sua acurácia
melhor_modelo = None
melhor_acuracia = 0

# Testar cada modelo individualmente e imprimir os resultados
for i, modelo_info in enumerate(melhores_10_redes):
    modelo = MLPClassifier(
        hidden_layer_sizes=modelo_info["hidden_layer_sizes"],
        max_iter=2000,
        tol=1e-7,
        learning_rate_init=modelo_info["learning_rate_init"],
        momentum=modelo_info["momentum"],
        solver="sgd",
        activation="relu",
        learning_rate="constant",
        verbose=0
    )
    modelo.fit(x_treino, y_de_treino)
    y_pred = modelo.predict(x_teste)
    accuracy = np.mean(y_pred == y_de_teste) * 100
    conf_matrix = confusion_matrix(y_de_teste, y_pred)

    # Verificar se esse modelo é o melhor até agora
    if accuracy > melhor_acuracia:
        melhor_acuracia = accuracy
        melhor_modelo = modelo

    # Imprimir os resultados do modelo atual
    print(f"Modelo {i+1}")
    print(f"Acurácia: {accuracy:.2f}")
    print(f"Matriz de Confusão:\n{conf_matrix}\n")



Modelo 1
Acurácia: 73.47
Matriz de Confusão:
[[13  2]
 [11 23]]



d:\Users\tiago\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(


Modelo 2
Acurácia: 67.35
Matriz de Confusão:
[[10  5]
 [11 23]]



d:\Users\tiago\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(


Modelo 3
Acurácia: 71.43
Matriz de Confusão:
[[10  5]
 [ 9 25]]



d:\Users\tiago\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(


Modelo 4
Acurácia: 69.39
Matriz de Confusão:
[[10  5]
 [10 24]]

Modelo 5
Acurácia: 69.39
Matriz de Confusão:
[[ 0 15]
 [ 0 34]]



d:\Users\tiago\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(


Modelo 6
Acurácia: 77.55
Matriz de Confusão:
[[11  4]
 [ 7 27]]



d:\Users\tiago\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(


Modelo 7
Acurácia: 75.51
Matriz de Confusão:
[[10  5]
 [ 7 27]]



d:\Users\tiago\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(


Modelo 8
Acurácia: 79.59
Matriz de Confusão:
[[11  4]
 [ 6 28]]

Modelo 9
Acurácia: 73.47
Matriz de Confusão:
[[10  5]
 [ 8 26]]

Modelo 10
Acurácia: 69.39
Matriz de Confusão:
[[ 7  8]
 [ 7 27]]



d:\Users\tiago\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(


Escrever a matriz de confusão da melhor rede:

In [10]:
# Imprimir os resultados do melhor modelo
print("Melhor Modelo:")
print(f"Acurácia: {melhor_acuracia:.2f}")
print("Matriz de Confusão:")
print(confusion_matrix(y_de_teste, melhor_modelo.predict(x_teste)))

Melhor Modelo:
Acurácia: 79.59
Matriz de Confusão:
[[11  4]
 [ 6 28]]
